import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NavBar } from "@/components/customer/Navbar";
import { PrimeReactProvider } from 'primereact/api';
import Chatbot from '@/components/customer/chatbot';
import { Toaster } from "react-hot-toast";
import { useState } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>

      <body className="bg-white transition-all ease-in-out relative">
        <PrimeReactProvider>
          <NavBar />
          {children}

          {/* Chatbot container */}
          <div className="fixed bottom-4 right-4 z-50">
            <Toaster
              position="top-right"
              reverseOrder={false}
            />
            <Chatbot />
          </div>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
